# Define stages used in the pipeline
stages:
  - build
  - test
  - deploy

# Job to build the project
build_job:
  stage: build
  script:
    - echo "Building the project..."

# Job to run tests
test_job:
  stage: test
  script:
    - echo "Running tests..."

# Job to deploy the project
deploy_job:
  stage: deploy
  script:
    - echo "Deploying the project..."
